/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-08-01 09:47:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SearchBus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <title>Online Bus Ticket Booking</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Theme CSS -->\n");
      out.write("    <link href=\"css/freelancer.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom Fonts -->\n");
      out.write("    <link href=\"vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("   \n");
      out.write("     <!-- Load jQuery from Google's CDN -->\n");
      out.write("    <!-- Load jQuery UI CSS  -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css\" />\n");
      out.write("   \n");
      out.write("    <!-- Load jQuery JS -->\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\n");
      out.write("    <!-- Load jQuery UI Main JS  -->\n");
      out.write("    <script src=\"http://code.jquery.com/ui/1.10.3/jquery-ui.js\"></script>\n");
      out.write("   \n");
      out.write("    <!-- Load SCRIPT.JS which will create datepicker for input field  -->\n");
      out.write("    \n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("   .bodyColor {\n");
      out.write("  text-align: center;\n");
      out.write("  /*background: #18BC9C;*/\n");
      out.write("  \tbackground: url(\"img/back.jpg\") 30% 30%;\n");
      out.write("        \n");
      out.write("  color: white;\n");
      out.write("} \n");
      out.write("  .form-control option {\n");
      out.write("      font-size:large;\n");
      out.write("      color:black;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<body id=\"page-top\" class=\"bodyColor\">\n");
      out.write("\n");
      out.write("    <!-- Navigation -->\n");
      out.write("    <nav id=\"mainNav\" class=\"navbar navbar-default navbar-fixed-top navbar-custom\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"#page-top\"><img style=\"position:fixed; left:1px;top:24px\"class=\"img-responsive\" src=\"img/bus.gif\" alt=\"\"></a>\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("            <div class=\"navbar-header page-scroll\">\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span> Menu <i class=\"fa fa-bars\"></i>\n");
      out.write("                </button>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                    <li class=\"hidden\">\n");
      out.write("                        <a href=\"#page-top\"></a>\n");
      out.write("                    </li>\n");
      out.write("                    \n");
      out.write("                    <li class=\"page-scroll\">\n");
      out.write("                      <p>  <a href=\"HomePage.html\">Back</a></p>\n");
      out.write("                    </li>\n");
      out.write("                    \n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-collapse -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.container-fluid -->\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div style=\"position:fixed; left:80px; top:200px;margin-bottom: 2cm;\"  >\n");
      out.write("<h2 style=\"margin-bottom: 2cm;\">\n");
      out.write("Online Bus Ticket Booking With Zero Booking Fee!!!!</h2>\n");
      out.write("\n");
      out.write(" \n");
      out.write("<form  id=\"searchBus\" name=\"searchBus\" action=\"test.html\" method=\"post\">\n");
      out.write("   <table style=\"margin-bottom: 2cm;\">\n");
      out.write("    <tr>\n");
      out.write("        <td>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("      \n");
      out.write("            <p  >From</p>\n");
      out.write("      <select class=\"form-control\"style=\"width:250Px; \" name=\"source\" id=\"source\" >\n");
      out.write("        <option > -- Select Source -- </option>\n");
      out.write("        <option>Chennai</option>\n");
      out.write("        <option>Trichy</option>\n");
      out.write("        <option>Madurai</option>\n");
      out.write("        <option>Tuticurin</option>\n");
      out.write("      </select>\n");
      out.write("           </div>\n");
      out.write("         </td>\n");
      out.write("        <td style=\"position:absolute;right: 350px;\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("             <p>To</p>\n");
      out.write("      <select class=\"form-control\"style=\"width:250Px\" name=\"destination\"  id=\"destination\" >\n");
      out.write("         <option > -- Select Destination -- </option>\n");
      out.write("        <option>Chennai</option>\n");
      out.write("        <option>Trichy</option>\n");
      out.write("        <option>Madurai</option>\n");
      out.write("        <option>Tuticurin</option>\n");
      out.write("      </select>\n");
      out.write("            </div>\n");
      out.write("        </td>\n");
      out.write("       \n");
      out.write("    \n");
      out.write("    </tr>\n");
      out.write("     \n");
      out.write("    \n");
      out.write("    </table>\n");
      out.write("     <p style=\"position:absolute;left:2Px;top:250px;margin-bottom: 2cm;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pick a Date\n");
      out.write("     <input name=\"dateOfTravel\" id=\"dateOfTravel\"  onchange=\"dateofTavel()\" style=\"position:absolute;left:2Px;color:black\" type=\"text\"  /></p>\n");
      out.write("     <button style=\"position:absolute;left:2Px;top:380px;\"type=\"submit\" onClick=\"sourceAndDestinationEvaluation()\" class=\"btn btn-danger\" >Select My Trip</button>\n");
      out.write("     <script>\n");
      out.write("  $(document).ready(\n");
      out.write("  \n");
      out.write("  /* This is the function that will get executed after the DOM is fully loaded */\n");
      out.write("  function () {\n");
      out.write("    $( \"#dateOfTravel\" ).datepicker({\n");
      out.write("      changeMonth: true,//this option for allowing user to select month\n");
      out.write("      changeYear: true ,//this option for allowing user to select from year range\n");
      out.write("      dateFormat: 'yy-mm-dd'\n");
      out.write("    });\n");
      out.write("  }\n");
      out.write("\n");
      out.write(");\n");
      out.write("  function sourceAndDestinationEvaluation() {\n");
      out.write("      var source = document.searchBus.source.value;\n");
      out.write("      var destination = document.searchBus.destination.value;\n");
      out.write("      var dateOfTravel =  document.searchBus.dateOfTravel.value;\n");
      out.write("      if(source == destination ){\n");
      out.write("    \t  alert(\"Source and Destination Should not be same.Please enter correct value\");\n");
      out.write("      }\n");
      out.write("      else if(source == \"-- Select Source --\"){\n");
      out.write("    \t  alert(\"Select Source City\");\n");
      out.write("      }\n");
      out.write("      else if(destination == \"-- Select Destination --\"){\n");
      out.write("    \t  alert(\"Select Destination City\");\n");
      out.write("      }\n");
      out.write("      if(dateOfTravel == \"\"){\n");
      out.write("\t\t  alert(\"Select Travel Date\");\n");
      out.write("\t  }\n");
      out.write("      \n");
      out.write("  } \n");
      out.write("  function dateofTavel() {\n");
      out.write("\t  var dateOfTravel =  $('#dateOfTravel').datepicker('getDate');\n");
      out.write("\t  var now = new Date();\n");
      out.write("\t  if(dateOfTravel < now){\n");
      out.write("\t\t  alert(\"Please Select Correct Date\");\n");
      out.write("\t  }\n");
      out.write("  }\n");
      out.write(" \n");
      out.write("  </script>\n");
      out.write("  \n");
      out.write("  </form>\n");
      out.write("  \n");
      out.write(" </div>\n");
      out.write(" \n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
